; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:heltec_wifi_lora_32_V4]
platform = espressif32
framework = arduino
board = heltec_wifi_lora_32_V4
board_build.variants_dir = variants
board_build.variant = heltec_V4
monitor_speed = 115200
monitor_echo = yes
monitor_filters = send_on_enter
build_flags = 
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
lib_deps = 
	heltecautomation/Heltec ESP32 Dev-Boards@^2.1.5
	jgromes/RadioLib@^7.6.0
